version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq-container
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bridged
  queues:
    build: .
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST_NAME=rabbitmq-container
    networks:
      - bridged
networks:
  bridged:
    driver: bridge

